networks:
  richs_pizza_network:
    driver: bridge

services:
  # Single Besu Node (Simplified for development)
  besu-dev:
    image: hyperledger/besu:24.1.2
    container_name: besu-dev
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - BESU_IDENTITY=richs-pizza-dev
    command: |
      --network-id=2024
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/node1/key
      --data-path=/opt/besu/data
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-http-api=ETH,NET,WEB3,IBFT,ADMIN,DEBUG
      --host-allowlist="*"
      --p2p-enabled=false
      --min-gas-price=0
      --miner-enabled=true
      --miner-coinbase=0x627306090abaB3A6e1400e9345bC60c78a8BEf57
      --logging=INFO
    volumes:
      - ./genesis-dev.json:/opt/besu/genesis.json:ro
      - ./keys:/opt/besu/keys:ro
      - besu_dev_data:/opt/besu/data
    ports:
      - "8545:8545"
    networks:
      - richs_pizza_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8545 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: richs_pizza_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=richs_pizza_traceability
      - POSTGRES_USER=richs_user
      - POSTGRES_PASSWORD=richs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - richs_pizza_network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U richs_user -d richs_pizza_traceability"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  besu_dev_data:
  postgres_data:
