version: "3.8"

networks:
  richs_pizza_network:
    driver: bridge

services:
  # Simplified Besu Node 1 (Primary validator)
  besu-node1:
    image: hyperledger/besu:24.1.2
    container_name: besu-node1
    restart: unless-stopped
    environment:
      - BESU_IDENTITY=richs-products-validator
    command: |
      --network-id=2024
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/node1/key
      --data-path=/opt/besu/data
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-http-api=ETH,NET,WEB3,IBFT
      --host-allowlist="*"
      --p2p-enabled=true
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --discovery-enabled=false
      --static-nodes-file=/opt/besu/static-nodes.json
      --min-gas-price=0
      --logging=INFO
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys:/opt/besu/keys
      - ./static-nodes.json:/opt/besu/static-nodes.json
      - besu_node1_data:/opt/besu/data
    ports:
      - "8545:8545"
      - "30303:30303"
    networks:
      - richs_pizza_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Besu Node 2 (Validator)
  besu-node2:
    image: hyperledger/besu:24.1.2
    container_name: besu-node2
    restart: unless-stopped
    environment:
      - BESU_IDENTITY=manufacturer-validator
    command: |
      --network-id=2024
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/node2/key
      --data-path=/opt/besu/data
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-http-api=ETH,NET,WEB3,IBFT
      --host-allowlist="*"
      --p2p-enabled=true
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --discovery-enabled=false
      --static-nodes-file=/opt/besu/static-nodes.json
      --min-gas-price=0
      --logging=INFO
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./keys:/opt/besu/keys
      - ./static-nodes.json:/opt/besu/static-nodes.json
      - besu_node2_data:/opt/besu/data
    ports:
      - "8546:8545"
      - "30304:30303"
    networks:
      - richs_pizza_network
    depends_on:
      - besu-node1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: richs_pizza_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=richs_pizza_traceability
      - POSTGRES_USER=richs_user
      - POSTGRES_PASSWORD=richs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - richs_pizza_network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U richs_user -d richs_pizza_traceability"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  besu_node1_data:
  besu_node2_data:
  postgres_data:
